version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/db:/var/lib/mysql
    container_name: mysql-5.7
    hostname: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: shipping_tracking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  web:
    build: .
    links: 
      - db
    container_name: web
    hostname: app
    ports:
      - "1337:1337"
  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbitmq-server"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     # RABBITMQ_DEFAULT_USER: "rabbitmq"
  #     # RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     # RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   labels:
  #     NAME: "rabbitmq"